apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo
  name: todo-deployment
    #namespace: todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - image: rishikeshops/react_django_app:latest
          name: todo
          ports:
            - containerPort: 8001

---

apiVersion: v1
kind: Service
metadata:
  name: todo-service
  labels:
    app: todo
      #namespace: todo
spec:
  type: LoadBalancer
  ports:
  - port: 8001
    targetPort: 8001
    nodePort: 31000
  selector:
    app: todo
